name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: echo "${{ secrets.KONECTY_KUBECONFIG }}" > $HOME/.kube/config

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd

    - name: Install yq
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository -y ppa:rmescandon/yq
        sudo apt-get update
        sudo apt-get install -y yq

    - name: Port forward to Argo CD server
      run: |
        kubectl port-forward service/argocd-server 8080:80 -n argocd &
      background: true

    - name: Log in to ArgoCD
      run: |
        argocd login localhost:8080 --username=${{ secrets.ARGO_LOGIN }} --password=${{ secrets.ARGO_PASSWORD }} --insecure

    - name: Read ArgoCD deploy template
      id: read-template
      run: |
        YAML_CONTENT=$(cat deploy/argo_deploy_template.yaml)
        APP_NAME=$(echo "$YAML_CONTENT" | yq '.application.name')
        REPO=$(echo "$YAML_CONTENT" | yq '.application.repo')
        PATH=$(echo "$YAML_CONTENT" | yq '.application.path')
        DEST_NAMESPACE=$(echo "$YAML_CONTENT" | yq '.application.dest_namespace')
        DEST_SERVER=$(echo "$YAML_CONTENT" | yq '.application.dest_server')
        PROJECT=$(echo "$YAML_CONTENT" | yq '.application.project')
        GRPC_WEB=$(echo "$YAML_CONTENT" | yq '.application.grpc_web')
        REVISION=$(echo "$YAML_CONTENT" | yq '.application.revision')
        LABELS=$(echo "$YAML_CONTENT" | yq '.application.labels[]')

        COMMAND="argocd app create $APP_NAME --repo $REPO --path $PATH --dest-namespace $DEST_NAMESPACE --dest-server $DEST_SERVER --project $PROJECT"
        if [ "$GRPC_WEB" = "true" ]; then
          COMMAND="$COMMAND --grpc-web"
        fi
        COMMAND="$COMMAND --revision $REVISION"
        for LABEL in $LABELS; do
          COMMAND="$COMMAND -l $LABEL"
        done

        echo "COMMAND=$COMMAND" >> $GITHUB_ENV

    - name: Create ArgoCD Application
      run: |
        $COMMAND
      env:
        COMMAND: ${{ env.COMMAND }}
